-- Generated by risk_model_workbench.
-- feature_tables=48, features=300
create table if not exists pdm_risk.pdm_risk_fujie_gcard_d01_d02_wide_feature_v6_1 as
select
  t1.uid,
  t1.mdl_dte,
  t1.ds,
  t1.blue_customer_flag,
  t1.ftr_30d_ord_flag,
  t1.ftr_30d_ord_amt,
  t1.prc_amt_xz_30d_3m,
  t1.ovd_amt_xz_30d_3m,
  t1.final_flag,
  t1.zc_level,
  t1.gcard_v2,
  t1.gcard_v4,
  t1.gcard_v5,
  t1.gcard_v6,
  t1.rand_flag0,
  t1.rand_flag1,
  t1.rand_flag2,
  t1.rand_flag3,
  t1.rand_flag4,
  t1.rand_flag5,
  t2.ord_apl_sum_prc_amt_90_day,
  t2.ord_apl_max_prc_amt_180_day,
  t2.his_90_day_csh_apl_ord_cnt_his_rto,
  t2.ord_apl_sum_prc_amt_360_day,
  t2.his_180_day_csh_apl_ord_cnt_his_rto,
  t2.his_360_day_csh_apl_ord_cnt,
  t2.ord_apl_fal_cnt_his,
  t2.ord_apl_min_prc_amt_his,
  t2.ddf_ato_fst_ord_crt_dte,
  t2.ddf_mdl_lst_ord_crt_dte,
  t2.pst_ord_apl_suc_max_prc_amt_180_day,
  t2.max_ddf_lag_crt_dte,
  t2.ddf_fst_adt_fst_ord_crt_dte_mnt,
  t2.max_ddf_suc_lag_crt_dte,
  t2.ord_apl_suc_max_stg_num_his,
  t2.fst_fal_ord_prc_amt,
  t2.ord_apl_suc_max_prc_amt_his,
  t2.ddf_fst_lst_ord_crt_dte,
  t2.min_ddf_lag_crt_tim_mnt,
  t2.ord_apl_fal_cnt_360_day,
  t2.ord_apl_suc_sum_prc_amt_90_day,
  t3.unpaid_principal_future_light_add_heavy,
  t3.his_light_limit_divide_btch_avl_limit,
  t3.light_d720_sum_faqi_stg_num_divide_heavy_d720_sum_faqi_stg_num,
  t4.d360_apl_ord_ddf_mdl_ord_crt_dte_min,
  t4.d180_apl_ord_days_cnt_all,
  t4.d30_d60_apl_ord_cnt_rat,
  t4.d360_apl_ord_cnt_all,
  t4.d30_d360_suc_ord_prc_amt_avg_rat_all,
  t4.d7_d360_suc_ord_prc_amt_avg_rat_all,
  t4.d180_suc_ord_cnt_all,
  t4.d30_d90_suc_ord_prc_amt_avg_rat_all,
  t4.d15_suc_ord_prc_amt_avg_all,
  t4.d30_apl_ord_ddf_mdl_ord_crt_dte_min,
  t4.d360_apl_ord_ddf_mdl_ord_crt_dte_max,
  t4.d360_suc_ord_ddf_mdl_ord_crt_dte_min,
  t4.d180_apl_ord_ddf_mdl_ord_crt_dte_max,
  t4.d60_d90_apl_ord_cnt_rat_all,
  t4.d90_apl_ord_prc_amt_avg,
  t4.d60_apl_ord_prc_amt_per_stg_avg_all,
  t4.d90_d180_apl_ord_cnt_rat,
  t4.d360_apl_ord_prc_amt_min,
  t4.d15_d360_apl_ord_prc_amt_avg_rat,
  t4.d60_apl_ord_prc_amt_min,
  t5.cnt_event_result_1_uid_recent_days_120,
  t5.cnt_other_info_cash_uid_recent_days_30,
  t5.first_day_diff_event_result_0_event_type_loan_all,
  t5.max_amt_other_info_manual_repay,
  t5.n_unique_other_info_event_type_credit,
  t5.succloan_stage_num_mean_all,
  t5.per_event_type_limit_all,
  t5.min_amt_event_type_credit_event_result_1,
  t5.median_amt_channel_hb_microcredit_lv1_all,
  t5.first_amt_event_type_credit_all,
  t5.div_amt_event_type_repay_loan,
  t5.cnt_event_type_limit_type_heavy_all,
  t5.cnt_event_type_loan_type_heavy_all,
  t5.stddev_day_diff_shift1_event_type_repay_all,
  t5.last_amt_channel_hb_microcredit_lv1_all,
  t5.min_amt_event_type_repay_recent_180,
  t5.max_amt_type_light,
  t5.succloan_day_diff_reud_stage_num_sum_all,
  t5.max_amt_event_type_repay_recent_60,
  t6.dau_90d,
  t6.max_con_dau_7d,
  t6.ddf_mdl_max_con_dau_dt_90d,
  t6.ddf_mdl_max_con_dau_dt_30d,
  t7.cnt_avg_ord_span_30d,
  t7.mdt_lst_30d_90d_ord_cnt_typ_btch_rte,
  t7.cnt_avg_ord_span_30d_90d,
  t8.ddf_lst_app_str_tim_to_mdl_tim_sec,
  t9.his_720_day_csh_apl_ord_cnt_his_rto,
  t9.ord_apl_cnt_07_12,
  t9.ord_apl_cnt_13_18,
  t10.rsk_avl_lmt_ch_les_10000_cnt_3m,
  t10.rsk_avl_lmt_ch_les_500_cnt_12m,
  t10.rsk_avl_lmt_ch_les_1000_cnt_3m,
  t10.rsk_avl_lmt_ch_les_5000_rate_1m,
  t10.used_rate_ch_grt_0p95_rate_1m,
  t10.used_rate_ch_grt_0p5_cnt_3m_suc,
  t10.used_rate_ch_grt_0p8_cnt_1m_suc,
  t10.min_rsk_lmt_rate_bt_ch_3m,
  t11.stg_pln_max_rep_prc_1m_his,
  t11.stg_pln_sum_rep_prc_his_fst_ord,
  t11.lst_rep_prc,
  t12.clk_cnt_14d,
  t13.min_rsk_lmt_rate_12m_bt_ch,
  t13.avg_avl_lmt_lft_rep_prc_3m_cash_1m,
  t13.max_avl_lmt_lft_rep_prc_1m_cash_3m,
  t13.min_avl_lmt_lft_rep_prc_2m_cash_3m,
  t13.rsk_lmt_rate_ch_1m_grt_0p2_rate_6m,
  t13.min_rsk_avl_lmt_12m_bt_ch,
  t13.rsk_avl_lmt_ch_1m_les_10000_cnt_12m,
  t13.min_rsk_avl_lmt_3m_bt_ch,
  t13.rsk_avl_lmt_ch_1m_les_500_cnt_3m,
  t13.rsk_lmt_rate_ch_1m_grt_0p9_cnt_6m,
  t13.rsk_avl_lmt_ch_1m_les_500_cnt_12m,
  t13.avg_avl_lmt_lft_rep_prc_all_cash_12m,
  t13.rsk_lmt_rate_ch_1m_grt_0p5_rate_6m,
  t13.rsk_avl_lmt_ch_1m_les_1000_rate_6m,
  t13.rsk_lmt_rate_ch_1m_grt_0p8_cnt_1m,
  t13.rsk_avl_lmt_ch_1m_les_500_rate_3m,
  t14.sum_avb_lmt_2m_v2,
  t14.cnt_avb_lmt_2m_v2,
  t14.avg_lmt_use_rat_2m_v2,
  t15.d360_max_faqi_prc_amt_divide_rsk_avl_lmt_cash,
  t15.d180_ontimrepay_thismon_sum_larger_than_rsk_avl_lmt_cash_count_sum,
  t15.d90_due_repay_amt_avg_divide_d90_faqi_trade_amt_avg,
  t15.d720_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
  t15.his_due_repay_amt_avg_divide_his_faqi_trade_amt_avg,
  t15.d720_faqi_trade_amt_larger_than_due_repay_amt_by_mon_count_sum,
  t15.d1080_due_repay_amt_sum_divide_d1080_faqi_trade_amt_sum,
  t15.d1080_avg_due_pay_amt_sum_by_mon_divide_rsk_adt_lmt_cash,
  t15.d1080_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  t15.his_max_faqi_prc_amt_divide_max_ontim_amt_sum_mon,
  t15.d180_unpaid_principal_tot_amt_t_day_divide_rsk_avl_lmt_cash_his_t_day_max,
  t15.his_due_repay_amt_sum_divide_his_faqi_trade_amt_sum,
  t15.d180_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  t15.d720_due_repay_amt_avg_divide_d720_faqi_trade_amt_avg,
  t15.d720_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  t15.his_trade_fail_count_mon_divide_his_trade_success_count_mon,
  t15.d90_max_due_prc_amt_divide_rsk_adt_lmt_cash,
  t15.d360_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
  t15.his_max_faqi_prc_amt_divide_max_due_pay_amt_sum_mon,
  t15.his_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon,
  t15.d1080_unpaid_principal_tot_amt_t_day_divide_rsk_adt_lmt_cash_his_t_day_max,
  t15.d1080_due_repay_amt_avg_divide_d1080_faqi_trade_amt_avg,
  t15.his_max_faqi_prc_amt_divide_unpaid_principal_tot,
  t15.d180_max_due_prc_amt_divide_d180_max_faqi_prc_amt,
  t15.d720_max_adv_repay_amt_divide_d720_max_faqi_prc_amt,
  t15.d720_trade_fail_count_mon_divide_his_trade_success_count_mon,
  t15.d360_ovdrepay_amt_sum_divide_ontimrepay_amt_sum,
  t15.d90_advrepay_amt_sum_divide_ontimrepay_amt_sum,
  t15.d180_max_ovd_repay_amt_divide_d180_max_fail_prc_amt,
  t15.d90_avg_due_pay_amt_sum_by_mon_divide_rsk_adt_lmt_cash,
  t15.d720_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon,
  t16.`6m_used_lmt_first_der_max`,
  t16.`6m_used_lmt_first_der_min`,
  t16.`18m_used_lmt_second_der_min`,
  t16.`6m_used_lmt_first_der_median`,
  t16.`18m_used_lmt_second_der_sum`,
  t16.`12m_used_lmt_second_der_sum`,
  t16.`12m_used_lmt_first_der_sum`,
  t16.`12m_used_lmt_first_der_mean_diff`,
  t16.`3m_used_lmt_second_der_sum`,
  t16.`3m_used_lmt_first_der_max`,
  t16.`3m_used_lmt_first_der_sum`,
  t16.`12m_used_lmt_first_der_avg`,
  t16.`6m_used_lmt_first_der_sum`,
  t16.`3m_used_lmt_first_der_mean_diff`,
  t16.`18m_used_lmt_first_der_sum`,
  t16.`6m_used_lmt_second_der_sum`,
  t16.`3m_used_lmt_second_der_mean_diff`,
  t16.`6m_used_lmt_second_der_min`,
  t16.`3m_used_lmt_first_der_great_0_count`,
  t16.`12m_used_lmt_second_der_max`,
  t16.`6m_used_lmt_first_der_mean_diff`,
  t16.`3m_used_lmt_first_der_small_0_sum`,
  t16.`18m_used_lmt_first_der_mean_rto`,
  t16.`18m_used_lmt_second_der_small_0_count`,
  t16.`3m_used_lmt_first_der_mean_rto`,
  t17.d90_aplord_suc_month_cnt,
  t17.d730_aplord_amt_grt_fst_month_rto,
  t18.stg_pln_sum_prc_amt_6m_12m_rto_ftr,
  t18.stg_pln_min_prc_amt_3m_ftr,
  t18.stg_pln_sum_prc_amt_1m_2m_rto_ftr,
  t18.stg_pln_sum_prc_amt_3m_6m_rto_ftr,
  t19.stg_pln_cnt_3m_ftr_adv_rto_all,
  t19.stg_pln_sum_prc_amt_1m_3m_ftr_rto_all,
  t19.stg_pln_sum_prc_amt_1m_ftr_his_rep_rto_all,
  t19.stg_pln_sum_prc_amt_12m_ftr_his_rep_rto_cash,
  t19.stg_pln_cnt_6m_12m_ftr_rto_all,
  t19.stg_pln_cnt_1m_3m_ftr_rto_all,
  t19.stg_pln_sum_prc_amt_6m_ftr_his_rto_all,
  t19.stg_pln_min_prc_amt_12m_ftr_his_rto_cash,
  t19.stg_pln_avg_prc_amt_6m_12m_ftr_rto_all,
  t19.stg_pln_max_prc_amt_12m_ftr_his_rep_rto_cash,
  t19.stg_pln_min_prc_amt_3m_6m_ftr_cash,
  t19.stg_pln_avg_prc_amt_2m_ftr_his_rto_all,
  t20.stg_pln_pay_off_sum_prc_amt_1m,
  t20.stg_pln_pay_off_max_prc_amt_14d,
  t20.max_ddf_rep_tim_dte_ovd_pls_rep_12m,
  t20.max_ddf_rep_tim_dte_adv,
  t20.min_ddf_rep_tim_dte_adv,
  t21.ddf_24m_rep_dte_neg_7_crt_dt_ord_cnt,
  t21.ddf_24m_rep_dte_neg_7_crt_dt_avg_prc_amt,
  t21.ddf_24m_rep_dte_neg_1_crt_dt_rep_prc_amt_rto,
  t21.ddf_24m_rep_dte_7_crt_dt_rep_prc_amt_rto,
  t21.ddf_36m_rep_dte_5_crt_dt_rep_prc_amt_rto,
  t21.ddf_36m_rep_dte_neg_5_crt_dt_rep_prc_amt_rto,
  t21.ddf_36m_rep_dte_0_crt_dt_rep_prc_amt_rto,
  t22.ddf_1m_rep_dte_3_crt_dt_rep_prc_amt,
  t22.ddf_3m_rep_dte_5_crt_dt_sum_prc_amt,
  t22.ddf_3m_rep_dte_neg_3_crt_dt_max_prc_amt,
  t22.ddf_12m_rep_dte_7_crt_dt_rep_prc_amt_rto,
  t22.ddf_12m_rep_dte_neg_1_crt_dt_rep_prc_amt_rto,
  t22.avg_ddf_rep_dte_ord_crt_tim_neg_7,
  t23.credit_reject_unique_fund_cnt_6m,
  t23.credit_unique_scene_cnt_12m,
  t23.credit_fund_level2_reject_cnt_36m,
  t23.credit_unique_scene_cnt_36m,
  t24.percent_true_followup_code_other_call_mode_manual_30d,
  t24.percent_true_followup_code_wfjt_is_can_contact_person_yes_30d,
  t24.percent_true_followup_code_wfjt_is_can_contact_person_yes_90d,
  t25.rsk_lmt_rate_ch_1m_grt_0p2_rate_36m,
  t25.avg_avl_lmt_lft_rep_prc_all_cash_36m,
  t25.rsk_lmt_rate_ch_1m_grt_0p5_rate_24m,
  t25.rsk_lmt_rate_ch_1m_grt_0p9_rate_24m,
  t25.rsk_lmt_rate_ch_1m_grt_0p95_rate_36m,
  t25.rsk_lmt_rate_ch_1m_grt_0p2_cnt_24m,
  t25.max_rsk_avl_lmt_24m_bt_ch,
  t25.max_avl_lmt_lft_rep_prc_1m_cash_36m,
  t25.avg_avl_lmt_lft_rep_prc_all_cash_24m,
  t26.`3m_repay_ftr_amt_first_der_great_0_count`,
  t26.`6m_repay_ftr_amt_first_der_mean_rto`,
  t26.`18m_repay_ftr_amt_first_der_mean_diff`,
  t26.`3m_repay_ftr_amt_first_der_min`,
  t26.`3m_repay_ftr_amt_first_der_mean_diff`,
  t26.`3m_repay_ftr_amt_first_der_mean_rto`,
  t26.`18m_repay_ftr_amt_second_der_mean_diff`,
  t27.m6_stg_pln_pmt_not_eng_cnt_max,
  t27.m6_payment_not_eng_mdl_crt_ddf_max,
  t28.ai_call_cnt_21d,
  t29.m1_stg_pln_d0_manual_rep_apl_suc_cnt_rat,
  t29.m6_stg_pln_d0_normal_batch_rep_apl_suc_cnt_rat,
  t29.m6_stg_pln_his_ovd_manual_deduct_rep_apl_fal_cnt_rat,
  t30.d1080_sum_repaid_interest_fee_sum_divide_d1080_principal_sum,
  t30.d90_repaid_interest_fee_sum,
  t30.d180_adv_repay_fee_sum,
  t30.d360_schedule_pay_penalty_max,
  t30.d1080_repaid_interest_fee_stddev,
  t30.d90_repaid_interest_fee_stddev,
  t30.d720_repaid_tot_fee_stddev,
  t31.`6thord_con_dsc_apply_amt_max`,
  t31.`6ord_apply_amt_first_der_mean_rto`,
  t31.`3ord_apply_amt_first_der_mean_diff`,
  t31.`3ord_apply_amt_second_der_great_0_sum`,
  t32.m3_rep_apl_stg_pln_cnt_max,
  t32.m1_manual_rep_apl_stg_pln_cnt_avg,
  t33.abf_1y_inter_1m_count_up,
  t33.bf_3m_inter_1m_sum_up,
  t33.af_1y_inter_3m_sum_up,
  t33.rsi_abf_1y_inter_3m,
  t34.m1_manual_rep_apl_suc_amt_sum,
  t34.m1_rep_apl_suc_amt_avg,
  t34.m3_manual_rep_apl_suc_amt_avg,
  t34.m1_manual_rep_apl_suc_amt_avg,
  t34.m6_normal_batch_rep_apl_suc_amt_avg,
  t34.m6_manual_rep_apl_suc_amt_avg,
  t34.m6_manual_rep_apl_suc_cnt_in_manual_rep_rat,
  t34.m3_manual_rep_apl_suc_amt_max,
  t34.m6_manual_tim_13_18_rep_apl_suc_cnt_rat,
  t34.m6_manual_tim_6_12_rep_apl_cnt_rat,
  t35.sum_talk_duration_180d,
  t35.sum_talk_duration_30d,
  t35.percent_true_call_mode_is_manual_called_phone_social_relations_is_family_30d,
  t36.`6stg_pln_repay_amt_first_der_median`,
  t36.`18m_repay_amt_first_der_mean_diff`,
  t36.`12stg_pln_repay_amt_first_der_mean_rto`,
  t36.`12m_repay_amt_first_der_mean_diff`,
  t36.`6stg_pln_repay_amt_second_der_median`,
  t36.`12m_repay_amt_first_der_sum`,
  t36.`3stg_pln_repay_amt_first_der_stddev`,
  t36.`36stg_pln_repay_amt_second_der_mean_diff`,
  t36.`24stg_pln_repay_amt_second_der_mean_rto`,
  t36.`12m_repay_amt_first_der_mean_rto`,
  t36.`12m_repay_amt_second_der_sum`,
  t36.`3stg_pln_repay_amt_second_der_mean_rto`,
  t36.`12m_repay_amt_first_der_median`,
  t36.`6stg_pln_repay_amt_first_der_min`,
  t36.`3stg_pln_repay_amt_first_der_mean_diff`,
  t36.`6stg_pln_repay_amt_first_der_mean_diff`,
  t36.`30stg_pln_repay_amt_second_der_mean_rto`,
  t37.d30_d60_his_rep_amt_sum_rat_btch,
  t37.lag_his_rep_amt_sum_per_mth_btch_rat_max,
  t38.max_rsk_avl_lmt_bjq_12m_all,
  t38.rsk_avl_lmt_ch_1m_les_500_cnt_bjq_12m,
  t38.rsk_avl_lmt_ch_1m_les_10000_cnt_bjq_12m,
  t38.rsk_lmt_rate_ch_1m_grt_0p5_rate_bjq_12m,
  t39.stg_pln_pay_off_sum_prc_amt_14d_1m_rto,
  t39.stg_pln_sum_prc_amt_1m_2m_rto,
  t39.stg_pln_pay_off_sum_prc_amt_7d_1m_rto,
  t40.dvc_cnt_cjj_7,
  t41.min_ddf_mdl_rep_dte_ovd_3d_pls_bjq,
  t41.stg_pln_pay_off_cnt_bjq_12m,
  t41.min_ddf_mdl_rep_dte_ovd_pls_bjq,
  t41.min_ddf_mdl_rep_dte_his_bjq,
  t42.ord_apl_suc_sum_prc_amt_360_day_13_18_bjq_12m,
  t42.ord_apl_cnt_360_day_00_03_bjq_12m,
  t43.stg_pln_pay_off_cnt_d0_rep_24m_rto,
  t44.stg_pln_cnt_adv_rep_bjq_12m_rto,
  t44.stg_pln_avg_prc_amt_bjq_12m_his,
  t45.stg_pln_sum_rep_prc_his_d0_mrn_pk_rto_v2,
  t46.m1_stg_pln_rep_apl_fal_cnt_mor_1_rep_apl_amt_sum,
  t46.m6_stg_pln_manual_rep_apl_cnt_avg,
  t46.m6_stg_pln_rep_apl_fal_cnt_equal_1_cnt_rat,
  t46.m6_stg_pln_normal_batch_rep_apl_cnt_min,
  t47.ddf_mdl_max_con_not_ovd_tqhk_rep_tim_12m,
  t48.stg_pln_sum_rep_prc_12m_his_d0_mrn_pk_rto,
  t49.stg_pln_sum_rep_prc_his_d0_mrn_zd_v2
from (
  select
    uid,
    mdl_dte,
    ds,
    blue_customer_flag,
    ftr_30d_ord_flag,
    ftr_30d_ord_amt,
    prc_amt_xz_30d_3m,
    ovd_amt_xz_30d_3m,
    final_flag,
    zc_level,
    gcard_v2,
    gcard_v4,
    gcard_v5,
    gcard_v6,
    rand_flag0,
    rand_flag1,
    rand_flag2,
    rand_flag3,
    rand_flag4,
    rand_flag5
  from pdm_risk.pdm_risk_gcard_base_sample_uid_ds_eva_ben_v6_1
  where ds is not null
) t1
left join (
  select
    uid,
    mdl_dte,
    ord_apl_sum_prc_amt_90_day,
    ord_apl_max_prc_amt_180_day,
    his_90_day_csh_apl_ord_cnt_his_rto,
    ord_apl_sum_prc_amt_360_day,
    his_180_day_csh_apl_ord_cnt_his_rto,
    his_360_day_csh_apl_ord_cnt,
    ord_apl_fal_cnt_his,
    ord_apl_min_prc_amt_his,
    ddf_ato_fst_ord_crt_dte,
    ddf_mdl_lst_ord_crt_dte,
    pst_ord_apl_suc_max_prc_amt_180_day,
    max_ddf_lag_crt_dte,
    ddf_fst_adt_fst_ord_crt_dte_mnt,
    max_ddf_suc_lag_crt_dte,
    ord_apl_suc_max_stg_num_his,
    fst_fal_ord_prc_amt,
    ord_apl_suc_max_prc_amt_his,
    ddf_fst_lst_ord_crt_dte,
    min_ddf_lag_crt_tim_mnt,
    ord_apl_fal_cnt_360_day,
    ord_apl_suc_sum_prc_amt_90_day
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_7fst_9all_10cur_11lst_orders_info_df_feature
  where ds is not null
) t2
  on t1.uid = t2.uid and t1.mdl_dte = t2.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    unpaid_principal_future_light_add_heavy,
    his_light_limit_divide_btch_avl_limit,
    light_d720_sum_faqi_stg_num_divide_heavy_d720_sum_faqi_stg_num
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_30light_cross_heavy_inner_behaviour_df_feature
  where ds is not null
) t3
  on t1.uid = t3.uid and t1.mdl_dte = t3.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    d360_apl_ord_ddf_mdl_ord_crt_dte_min,
    d180_apl_ord_days_cnt_all,
    d30_d60_apl_ord_cnt_rat,
    d360_apl_ord_cnt_all,
    d30_d360_suc_ord_prc_amt_avg_rat_all,
    d7_d360_suc_ord_prc_amt_avg_rat_all,
    d180_suc_ord_cnt_all,
    d30_d90_suc_ord_prc_amt_avg_rat_all,
    d15_suc_ord_prc_amt_avg_all,
    d30_apl_ord_ddf_mdl_ord_crt_dte_min,
    d360_apl_ord_ddf_mdl_ord_crt_dte_max,
    d360_suc_ord_ddf_mdl_ord_crt_dte_min,
    d180_apl_ord_ddf_mdl_ord_crt_dte_max,
    d60_d90_apl_ord_cnt_rat_all,
    d90_apl_ord_prc_amt_avg,
    d60_apl_ord_prc_amt_per_stg_avg_all,
    d90_d180_apl_ord_cnt_rat,
    d360_apl_ord_prc_amt_min,
    d15_d360_apl_ord_prc_amt_avg_rat,
    d60_apl_ord_prc_amt_min
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dz_model_final_order_info_df_feature
  where ds is not null
) t4
  on t1.uid = t4.uid and t1.mdl_dte = t4.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    cnt_event_result_1_uid_recent_days_120,
    cnt_other_info_cash_uid_recent_days_30,
    first_day_diff_event_result_0_event_type_loan_all,
    max_amt_other_info_manual_repay,
    n_unique_other_info_event_type_credit,
    succloan_stage_num_mean_all,
    per_event_type_limit_all,
    min_amt_event_type_credit_event_result_1,
    median_amt_channel_hb_microcredit_lv1_all,
    first_amt_event_type_credit_all,
    div_amt_event_type_repay_loan,
    cnt_event_type_limit_type_heavy_all,
    cnt_event_type_loan_type_heavy_all,
    stddev_day_diff_shift1_event_type_repay_all,
    last_amt_channel_hb_microcredit_lv1_all,
    min_amt_event_type_repay_recent_180,
    max_amt_type_light,
    succloan_day_diff_reud_stage_num_sum_all,
    max_amt_event_type_repay_recent_60
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_22pip_heavy_cross_info_df_feature
  where ds is not null
) t5
  on t1.uid = t5.uid and t1.mdl_dte = t5.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    dau_90d,
    max_con_dau_7d,
    ddf_mdl_max_con_dau_dt_90d,
    ddf_mdl_max_con_dau_dt_30d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_dau_feature
  where ds is not null
) t6
  on t1.uid = t6.uid and t1.mdl_dte = t6.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    cnt_avg_ord_span_30d,
    mdt_lst_30d_90d_ord_cnt_typ_btch_rte,
    cnt_avg_ord_span_30d_90d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_22order_calculate_stage_order_info_df_feature
  where ds is not null
) t7
  on t1.uid = t7.uid and t1.mdl_dte = t7.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ddf_lst_app_str_tim_to_mdl_tim_sec
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_device_extra_1_df_feature
  where ds is not null
) t8
  on t1.uid = t8.uid and t1.mdl_dte = t8.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    his_720_day_csh_apl_ord_cnt_his_rto,
    ord_apl_cnt_07_12,
    ord_apl_cnt_13_18
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_7fst_9all_10cur_11lst_orders_info_new_df_feature
  where ds is not null
) t9
  on t1.uid = t9.uid and t1.mdl_dte = t9.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    rsk_avl_lmt_ch_les_10000_cnt_3m,
    rsk_avl_lmt_ch_les_500_cnt_12m,
    rsk_avl_lmt_ch_les_1000_cnt_3m,
    rsk_avl_lmt_ch_les_5000_rate_1m,
    used_rate_ch_grt_0p95_rate_1m,
    used_rate_ch_grt_0p5_cnt_3m_suc,
    used_rate_ch_grt_0p8_cnt_1m_suc,
    min_rsk_lmt_rate_bt_ch_3m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dz_model_account_lmt_feature_sample_final_df_feature
  where ds is not null
) t10
  on t1.uid = t10.uid and t1.mdl_dte = t10.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_max_rep_prc_1m_his,
    stg_pln_sum_rep_prc_his_fst_ord,
    lst_rep_prc
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_ability_df_feature
  where ds is not null
) t11
  on t1.uid = t11.uid and t1.mdl_dte = t11.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    clk_cnt_14d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_page_view_n_click_cnt_feature
  where ds is not null
) t12
  on t1.uid = t12.uid and t1.mdl_dte = t12.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    min_rsk_lmt_rate_12m_bt_ch,
    avg_avl_lmt_lft_rep_prc_3m_cash_1m,
    max_avl_lmt_lft_rep_prc_1m_cash_3m,
    min_avl_lmt_lft_rep_prc_2m_cash_3m,
    rsk_lmt_rate_ch_1m_grt_0p2_rate_6m,
    min_rsk_avl_lmt_12m_bt_ch,
    rsk_avl_lmt_ch_1m_les_10000_cnt_12m,
    min_rsk_avl_lmt_3m_bt_ch,
    rsk_avl_lmt_ch_1m_les_500_cnt_3m,
    rsk_lmt_rate_ch_1m_grt_0p9_cnt_6m,
    rsk_avl_lmt_ch_1m_les_500_cnt_12m,
    avg_avl_lmt_lft_rep_prc_all_cash_12m,
    rsk_lmt_rate_ch_1m_grt_0p5_rate_6m,
    rsk_avl_lmt_ch_1m_les_1000_rate_6m,
    rsk_lmt_rate_ch_1m_grt_0p8_cnt_1m,
    rsk_avl_lmt_ch_1m_les_500_rate_3m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_df_feature
  where ds is not null
) t13
  on t1.uid = t13.uid and t1.mdl_dte = t13.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    sum_avb_lmt_2m_v2,
    cnt_avb_lmt_2m_v2,
    avg_lmt_use_rat_2m_v2
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_5account_extra_df_feature
  where ds is not null
) t14
  on t1.uid = t14.uid and t1.mdl_dte = t14.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    d360_max_faqi_prc_amt_divide_rsk_avl_lmt_cash,
    d180_ontimrepay_thismon_sum_larger_than_rsk_avl_lmt_cash_count_sum,
    d90_due_repay_amt_avg_divide_d90_faqi_trade_amt_avg,
    d720_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
    his_due_repay_amt_avg_divide_his_faqi_trade_amt_avg,
    d720_faqi_trade_amt_larger_than_due_repay_amt_by_mon_count_sum,
    d1080_due_repay_amt_sum_divide_d1080_faqi_trade_amt_sum,
    d1080_avg_due_pay_amt_sum_by_mon_divide_rsk_adt_lmt_cash,
    d1080_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
    his_max_faqi_prc_amt_divide_max_ontim_amt_sum_mon,
    d180_unpaid_principal_tot_amt_t_day_divide_rsk_avl_lmt_cash_his_t_day_max,
    his_due_repay_amt_sum_divide_his_faqi_trade_amt_sum,
    d180_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
    d720_due_repay_amt_avg_divide_d720_faqi_trade_amt_avg,
    d720_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
    his_trade_fail_count_mon_divide_his_trade_success_count_mon,
    d90_max_due_prc_amt_divide_rsk_adt_lmt_cash,
    d360_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
    his_max_faqi_prc_amt_divide_max_due_pay_amt_sum_mon,
    his_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon,
    d1080_unpaid_principal_tot_amt_t_day_divide_rsk_adt_lmt_cash_his_t_day_max,
    d1080_due_repay_amt_avg_divide_d1080_faqi_trade_amt_avg,
    his_max_faqi_prc_amt_divide_unpaid_principal_tot,
    d180_max_due_prc_amt_divide_d180_max_faqi_prc_amt,
    d720_max_adv_repay_amt_divide_d720_max_faqi_prc_amt,
    d720_trade_fail_count_mon_divide_his_trade_success_count_mon,
    d360_ovdrepay_amt_sum_divide_ontimrepay_amt_sum,
    d90_advrepay_amt_sum_divide_ontimrepay_amt_sum,
    d180_max_ovd_repay_amt_divide_d180_max_fail_prc_amt,
    d90_avg_due_pay_amt_sum_by_mon_divide_rsk_adt_lmt_cash,
    d720_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_25_cross_inner_behaviour_df_feature
  where ds is not null
) t15
  on t1.uid = t15.uid and t1.mdl_dte = t15.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    `6m_used_lmt_first_der_max`,
    `6m_used_lmt_first_der_min`,
    `18m_used_lmt_second_der_min`,
    `6m_used_lmt_first_der_median`,
    `18m_used_lmt_second_der_sum`,
    `12m_used_lmt_second_der_sum`,
    `12m_used_lmt_first_der_sum`,
    `12m_used_lmt_first_der_mean_diff`,
    `3m_used_lmt_second_der_sum`,
    `3m_used_lmt_first_der_max`,
    `3m_used_lmt_first_der_sum`,
    `12m_used_lmt_first_der_avg`,
    `6m_used_lmt_first_der_sum`,
    `3m_used_lmt_first_der_mean_diff`,
    `18m_used_lmt_first_der_sum`,
    `6m_used_lmt_second_der_sum`,
    `3m_used_lmt_second_der_mean_diff`,
    `6m_used_lmt_second_der_min`,
    `3m_used_lmt_first_der_great_0_count`,
    `12m_used_lmt_second_der_max`,
    `6m_used_lmt_first_der_mean_diff`,
    `3m_used_lmt_first_der_small_0_sum`,
    `18m_used_lmt_first_der_mean_rto`,
    `18m_used_lmt_second_der_small_0_count`,
    `3m_used_lmt_first_der_mean_rto`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_used_lmt_trend_time_series_df_feature
  where ds is not null
) t16
  on t1.uid = t16.uid and t1.mdl_dte = t16.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    d90_aplord_suc_month_cnt,
    d730_aplord_amt_grt_fst_month_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_off_dp_dz_inner_behavior_order_enhanced_aggregation_feature
  where ds is not null
) t17
  on t1.uid = t17.uid and t1.mdl_dte = t17.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_sum_prc_amt_6m_12m_rto_ftr,
    stg_pln_min_prc_amt_3m_ftr,
    stg_pln_sum_prc_amt_1m_2m_rto_ftr,
    stg_pln_sum_prc_amt_3m_6m_rto_ftr
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_14ftr_rep_pressure_df_feature
  where ds is not null
) t18
  on t1.uid = t18.uid and t1.mdl_dte = t18.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_cnt_3m_ftr_adv_rto_all,
    stg_pln_sum_prc_amt_1m_3m_ftr_rto_all,
    stg_pln_sum_prc_amt_1m_ftr_his_rep_rto_all,
    stg_pln_sum_prc_amt_12m_ftr_his_rep_rto_cash,
    stg_pln_cnt_6m_12m_ftr_rto_all,
    stg_pln_cnt_1m_3m_ftr_rto_all,
    stg_pln_sum_prc_amt_6m_ftr_his_rto_all,
    stg_pln_min_prc_amt_12m_ftr_his_rto_cash,
    stg_pln_avg_prc_amt_6m_12m_ftr_rto_all,
    stg_pln_max_prc_amt_12m_ftr_his_rep_rto_cash,
    stg_pln_min_prc_amt_3m_6m_ftr_cash,
    stg_pln_avg_prc_amt_2m_ftr_his_rto_all
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_14ftr_rep_pressure_trend_df_feature
  where ds is not null
) t19
  on t1.uid = t19.uid and t1.mdl_dte = t19.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_pay_off_sum_prc_amt_1m,
    stg_pln_pay_off_max_prc_amt_14d,
    max_ddf_rep_tim_dte_ovd_pls_rep_12m,
    max_ddf_rep_tim_dte_adv,
    min_ddf_rep_tim_dte_adv
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_df_feature
  where ds is not null
) t20
  on t1.uid = t20.uid and t1.mdl_dte = t20.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ddf_24m_rep_dte_neg_7_crt_dt_ord_cnt,
    ddf_24m_rep_dte_neg_7_crt_dt_avg_prc_amt,
    ddf_24m_rep_dte_neg_1_crt_dt_rep_prc_amt_rto,
    ddf_24m_rep_dte_7_crt_dt_rep_prc_amt_rto,
    ddf_36m_rep_dte_5_crt_dt_rep_prc_amt_rto,
    ddf_36m_rep_dte_neg_5_crt_dt_rep_prc_amt_rto,
    ddf_36m_rep_dte_0_crt_dt_rep_prc_amt_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_16draw_repay_crossed_new_df_feature
  where ds is not null
) t21
  on t1.uid = t21.uid and t1.mdl_dte = t21.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ddf_1m_rep_dte_3_crt_dt_rep_prc_amt,
    ddf_3m_rep_dte_5_crt_dt_sum_prc_amt,
    ddf_3m_rep_dte_neg_3_crt_dt_max_prc_amt,
    ddf_12m_rep_dte_7_crt_dt_rep_prc_amt_rto,
    ddf_12m_rep_dte_neg_1_crt_dt_rep_prc_amt_rto,
    avg_ddf_rep_dte_ord_crt_tim_neg_7
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_16draw_repay_crossed_df_feature
  where ds is not null
) t22
  on t1.uid = t22.uid and t1.mdl_dte = t22.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    credit_reject_unique_fund_cnt_6m,
    credit_unique_scene_cnt_12m,
    credit_fund_level2_reject_cnt_36m,
    credit_unique_scene_cnt_36m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_31light_credit_trade_cross_df_feature
  where ds is not null
) t23
  on t1.uid = t23.uid and t1.mdl_dte = t23.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    percent_true_followup_code_other_call_mode_manual_30d,
    percent_true_followup_code_wfjt_is_can_contact_person_yes_30d,
    percent_true_followup_code_wfjt_is_can_contact_person_yes_90d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dh_model_final_13collection_notes_trend_features_feature
  where ds is not null
) t24
  on t1.uid = t24.uid and t1.mdl_dte = t24.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    rsk_lmt_rate_ch_1m_grt_0p2_rate_36m,
    avg_avl_lmt_lft_rep_prc_all_cash_36m,
    rsk_lmt_rate_ch_1m_grt_0p5_rate_24m,
    rsk_lmt_rate_ch_1m_grt_0p9_rate_24m,
    rsk_lmt_rate_ch_1m_grt_0p95_rate_36m,
    rsk_lmt_rate_ch_1m_grt_0p2_cnt_24m,
    max_rsk_avl_lmt_24m_bt_ch,
    max_avl_lmt_lft_rep_prc_1m_cash_36m,
    avg_avl_lmt_lft_rep_prc_all_cash_24m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_new_df_feature
  where ds is not null
) t25
  on t1.uid = t25.uid and t1.mdl_dte = t25.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    `3m_repay_ftr_amt_first_der_great_0_count`,
    `6m_repay_ftr_amt_first_der_mean_rto`,
    `18m_repay_ftr_amt_first_der_mean_diff`,
    `3m_repay_ftr_amt_first_der_min`,
    `3m_repay_ftr_amt_first_der_mean_diff`,
    `3m_repay_ftr_amt_first_der_mean_rto`,
    `18m_repay_ftr_amt_second_der_mean_diff`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_ftr_rep_trend_time_series_df_feature
  where ds is not null
) t26
  on t1.uid = t26.uid and t1.mdl_dte = t26.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    m6_stg_pln_pmt_not_eng_cnt_max,
    m6_payment_not_eng_mdl_crt_ddf_max
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_repayment_deduct_info_df_feature
  where ds is not null
) t27
  on t1.uid = t27.uid and t1.mdl_dte = t27.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ai_call_cnt_21d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dh_model_15ai_call_record_feature
  where ds is not null
) t28
  on t1.uid = t28.uid and t1.mdl_dte = t28.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    m1_stg_pln_d0_manual_rep_apl_suc_cnt_rat,
    m6_stg_pln_d0_normal_batch_rep_apl_suc_cnt_rat,
    m6_stg_pln_his_ovd_manual_deduct_rep_apl_fal_cnt_rat
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_3_feature
  where ds is not null
) t29
  on t1.uid = t29.uid and t1.mdl_dte = t29.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    d1080_sum_repaid_interest_fee_sum_divide_d1080_principal_sum,
    d90_repaid_interest_fee_sum,
    d180_adv_repay_fee_sum,
    d360_schedule_pay_penalty_max,
    d1080_repaid_interest_fee_stddev,
    d90_repaid_interest_fee_stddev,
    d720_repaid_tot_fee_stddev
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_26_lending_costs_detail_df_feature
  where ds is not null
) t30
  on t1.uid = t30.uid and t1.mdl_dte = t30.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    `6thord_con_dsc_apply_amt_max`,
    `6ord_apply_amt_first_der_mean_rto`,
    `3ord_apply_amt_first_der_mean_diff`,
    `3ord_apply_amt_second_der_great_0_sum`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_his_apply_trend_time_series_df_feature
  where ds is not null
) t31
  on t1.uid = t31.uid and t1.mdl_dte = t31.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    m3_rep_apl_stg_pln_cnt_max,
    m1_manual_rep_apl_stg_pln_cnt_avg
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_2_feature
  where ds is not null
) t32
  on t1.uid = t32.uid and t1.mdl_dte = t32.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    abf_1y_inter_1m_count_up,
    bf_3m_inter_1m_sum_up,
    af_1y_inter_3m_sum_up,
    rsi_abf_1y_inter_3m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_23changzhai_trend_df_feature
  where ds is not null
) t33
  on t1.uid = t33.uid and t1.mdl_dte = t33.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    m1_manual_rep_apl_suc_amt_sum,
    m1_rep_apl_suc_amt_avg,
    m3_manual_rep_apl_suc_amt_avg,
    m1_manual_rep_apl_suc_amt_avg,
    m6_normal_batch_rep_apl_suc_amt_avg,
    m6_manual_rep_apl_suc_amt_avg,
    m6_manual_rep_apl_suc_cnt_in_manual_rep_rat,
    m3_manual_rep_apl_suc_amt_max,
    m6_manual_tim_13_18_rep_apl_suc_cnt_rat,
    m6_manual_tim_6_12_rep_apl_cnt_rat
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_1_feature
  where ds is not null
) t34
  on t1.uid = t34.uid and t1.mdl_dte = t34.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    sum_talk_duration_180d,
    sum_talk_duration_30d,
    percent_true_call_mode_is_manual_called_phone_social_relations_is_family_30d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dh_model_final_13collection_call_info_trend_features_di_feature
  where ds is not null
) t35
  on t1.uid = t35.uid and t1.mdl_dte = t35.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    `6stg_pln_repay_amt_first_der_median`,
    `18m_repay_amt_first_der_mean_diff`,
    `12stg_pln_repay_amt_first_der_mean_rto`,
    `12m_repay_amt_first_der_mean_diff`,
    `6stg_pln_repay_amt_second_der_median`,
    `12m_repay_amt_first_der_sum`,
    `3stg_pln_repay_amt_first_der_stddev`,
    `36stg_pln_repay_amt_second_der_mean_diff`,
    `24stg_pln_repay_amt_second_der_mean_rto`,
    `12m_repay_amt_first_der_mean_rto`,
    `12m_repay_amt_second_der_sum`,
    `3stg_pln_repay_amt_second_der_mean_rto`,
    `12m_repay_amt_first_der_median`,
    `6stg_pln_repay_amt_first_der_min`,
    `3stg_pln_repay_amt_first_der_mean_diff`,
    `6stg_pln_repay_amt_first_der_mean_diff`,
    `30stg_pln_repay_amt_second_der_mean_rto`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_his_rep_trend_time_series_df_feature
  where ds is not null
) t36
  on t1.uid = t36.uid and t1.mdl_dte = t36.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    d30_d60_his_rep_amt_sum_rat_btch,
    lag_his_rep_amt_sum_per_mth_btch_rat_max
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_12his_rep_pressure_trend_df_feature
  where ds is not null
) t37
  on t1.uid = t37.uid and t1.mdl_dte = t37.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    max_rsk_avl_lmt_bjq_12m_all,
    rsk_avl_lmt_ch_1m_les_500_cnt_bjq_12m,
    rsk_avl_lmt_ch_1m_les_10000_cnt_bjq_12m,
    rsk_lmt_rate_ch_1m_grt_0p5_rate_bjq_12m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_jqh_df_feature
  where ds is not null
) t38
  on t1.uid = t38.uid and t1.mdl_dte = t38.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_pay_off_sum_prc_amt_14d_1m_rto,
    stg_pln_sum_prc_amt_1m_2m_rto,
    stg_pln_pay_off_sum_prc_amt_7d_1m_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_derived_df_feature
  where ds is not null
) t39
  on t1.uid = t39.uid and t1.mdl_dte = t39.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    dvc_cnt_cjj_7
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_device_extra_2_df_feature
  where ds is not null
) t40
  on t1.uid = t40.uid and t1.mdl_dte = t40.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    min_ddf_mdl_rep_dte_ovd_3d_pls_bjq,
    stg_pln_pay_off_cnt_bjq_12m,
    min_ddf_mdl_rep_dte_ovd_pls_bjq,
    min_ddf_mdl_rep_dte_his_bjq
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_jqh_df_feature
  where ds is not null
) t41
  on t1.uid = t41.uid and t1.mdl_dte = t41.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ord_apl_suc_sum_prc_amt_360_day_13_18_bjq_12m,
    ord_apl_cnt_360_day_00_03_bjq_12m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_7fst_9all_10cur_11lst_orders_info_jqh_df_feature
  where ds is not null
) t42
  on t1.uid = t42.uid and t1.mdl_dte = t42.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_pay_off_cnt_d0_rep_24m_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_derived_new_df_feature
  where ds is not null
) t43
  on t1.uid = t43.uid and t1.mdl_dte = t43.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_cnt_adv_rep_bjq_12m_rto,
    stg_pln_avg_prc_amt_bjq_12m_his
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_derived_jqh_df_feature
  where ds is not null
) t44
  on t1.uid = t44.uid and t1.mdl_dte = t44.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_sum_rep_prc_his_d0_mrn_pk_rto_v2
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_ability_derived_v2_df_feature
  where ds is not null
) t45
  on t1.uid = t45.uid and t1.mdl_dte = t45.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    m1_stg_pln_rep_apl_fal_cnt_mor_1_rep_apl_amt_sum,
    m6_stg_pln_manual_rep_apl_cnt_avg,
    m6_stg_pln_rep_apl_fal_cnt_equal_1_cnt_rat,
    m6_stg_pln_normal_batch_rep_apl_cnt_min
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_4_feature
  where ds is not null
) t46
  on t1.uid = t46.uid and t1.mdl_dte = t46.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    ddf_mdl_max_con_not_ovd_tqhk_rep_tim_12m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_final_2tqhk_reptim_360d_con_feature_feature
  where ds is not null
) t47
  on t1.uid = t47.uid and t1.mdl_dte = t47.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_sum_rep_prc_12m_his_d0_mrn_pk_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_ability_derived_df_feature
  where ds is not null
) t48
  on t1.uid = t48.uid and t1.mdl_dte = t48.mdl_dte
left join (
  select
    uid,
    mdl_dte,
    stg_pln_sum_rep_prc_his_d0_mrn_zd_v2
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_ability_v2_df_feature
  where ds is not null
) t49
  on t1.uid = t49.uid and t1.mdl_dte = t49.mdl_dte
;
