-- Generated by jingying_model_agent.
-- Purpose: full-row modeling sample extraction with all configured non-feature columns plus refined selected features only.
-- non_feature_columns=26, selected_features=96, feature_tables=32
-- non_feature_source=projects/2026-05-fujie-gcard-v1/configs/feature_select.yaml: feature_select.metadata.sample_columns
-- feature_list=projects/2026-05-fujie-gcard-v1/runs/feature_refine_feather/final_500_features.txt
-- feature_map=projects/2026-05-fujie-gcard-v1/runs/d01_d02_batch_select/results/d01_d02_wide_feature_map.csv
-- Note: no rand_flag sampling and no limit are applied; this is full-row extraction.
select
  t1.sample_row_num,
  t1.uid,
  t1.mdl_dte,
  t1.blue_customer_flag,
  t1.ftr_30d_ord_flag,
  t1.ftr_30d_ord_amt,
  t1.prc_amt_xz_30d_3m,
  t1.ovd_amt_xz_30d_3m,
  t1.liushi_days,
  t1.due_date_flag,
  t1.final_flag,
  t1.fq_diff_grp,
  t1.mob_group,
  t1.zc_level,
  t1.gd_lmt_grp,
  t1.gcard_v2,
  t1.gcard_v4,
  t1.gcard_v5,
  t1.gcard_v6,
  t1.rand_flag0,
  t1.rand_flag1,
  t1.rand_flag2,
  t1.rand_flag3,
  t1.rand_flag4,
  t1.rand_flag5,
  t1.ds,
  t2.ord_apl_sum_prc_amt_90_day,
  t2.ord_apl_max_prc_amt_180_day,
  t2.ord_apl_sum_prc_amt_360_day,
  t2.his_180_day_csh_apl_ord_cnt_his_rto,
  t2.his_360_day_csh_apl_ord_cnt,
  t2.his_360_day_csh_apl_ord_cnt_his_rto,
  t2.ord_apl_min_prc_amt_his,
  t2.ord_apl_fal_cnt_his,
  t2.ord_apl_cnt_90_day_07_12,
  t2.ord_apl_fal_cnt_360_day,
  t2.his_90_day_csh_apl_ord_cnt_his_rto,
  t3.d360_apl_ord_ddf_mdl_ord_crt_dte_min,
  t3.d180_apl_ord_days_cnt_all,
  t3.d360_apl_ord_cnt_all,
  t3.d360_apl_ord_prc_amt_min,
  t3.d360_apl_ord_ddf_mdl_ord_crt_dte_max,
  t3.d60_d90_apl_ord_cnt_rat_all,
  t3.d15_d360_apl_ord_prc_amt_avg_rat,
  t3.d30_d360_suc_ord_prc_amt_avg_rat_all,
  t3.d30_d90_suc_ord_prc_amt_avg_rat_all,
  t4.unpaid_principal_future_light_add_heavy,
  t5.dau_90d,
  t5.ddf_mdl_max_con_dau_dt_90d,
  t5.max_con_dau_7d,
  t6.cnt_event_result_1_uid_recent_days_120,
  t6.cnt_other_info_cash_uid_recent_days_30,
  t6.first_day_diff_event_result_0_event_type_loan_all,
  t6.max_amt_other_info_manual_repay,
  t6.div_amt_event_type_repay_loan,
  t7.ddf_lst_app_str_tim_to_mdl_tim_sec,
  t8.cnt_avg_ord_span_30d,
  t8.cnt_avg_ord_span_30d_90d,
  t9.d90_aplord_suc_month_cnt,
  t10.clk_cnt_14d,
  t11.rsk_avl_lmt_ch_les_500_cnt_12m,
  t11.rsk_avl_lmt_ch_les_10000_cnt_3m,
  t12.stg_pln_max_rep_prc_1m_his,
  t13.m1_stg_pln_d0_rep_apl_cnt,
  t13.m6_stg_pln_d0_normal_batch_rep_apl_suc_cnt_rat,
  t14.his_720_day_csh_apl_ord_cnt_his_rto,
  t14.ord_apl_cnt_07_12,
  t15.stg_pln_sum_prc_amt_12m_ftr_his_rep_rto_cash,
  t15.stg_pln_sum_prc_amt_6m_12m_ftr_rto_cash,
  t15.stg_pln_cnt_3m_ftr_adv_rto_all,
  t16.d360_due_repay_amt_avg_divide_d360_faqi_trade_amt_avg,
  t16.his_due_repay_amt_sum_divide_his_faqi_trade_amt_sum,
  t16.d720_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  t16.d1080_due_repay_amt_sum_divide_d1080_faqi_trade_amt_sum,
  t16.his_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon,
  t16.d90_due_repay_amt_avg_divide_d90_faqi_trade_amt_avg,
  t16.d360_max_faqi_prc_amt_divide_rsk_avl_lmt_cash,
  t16.his_due_repay_amt_avg_divide_his_faqi_trade_amt_avg,
  t16.d1080_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  t16.d180_due_repay_amt_avg_divide_d180_faqi_trade_amt_avg,
  t16.d180_unpaid_principal_tot_amt_t_day_divide_rsk_avl_lmt_cash_his_t_day_max,
  t16.his_max_due_prc_amt_divide_his_max_faqi_prc_amt,
  t16.d1080_due_repay_amt_avg_divide_d1080_faqi_trade_amt_avg,
  t16.his_max_faqi_prc_amt_divide_max_ontim_amt_sum_mon,
  t16.d180_ontimrepay_thismon_sum_larger_than_rsk_avl_lmt_cash_count_sum,
  t16.d720_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
  t16.his_max_faqi_prc_amt_divide_unpaid_principal_tot,
  t16.d720_due_repay_amt_sum_divide_d720_faqi_trade_amt_sum,
  t16.his_trade_fail_count_mon_divide_his_trade_success_count_mon,
  t17.`18m_used_lmt_second_der_min`,
  t17.`6m_used_lmt_first_der_min`,
  t17.`6m_used_lmt_second_der_min`,
  t17.`12m_used_lmt_second_der_sum`,
  t17.`6m_used_lmt_first_der_sum`,
  t17.`12m_used_lmt_second_der_mean_diff`,
  t17.`6m_used_lmt_second_der_sum`,
  t17.`18m_used_lmt_first_der_sum`,
  t17.`6m_used_lmt_first_der_max`,
  t17.`3m_used_lmt_second_der_sum`,
  t18.avg_avl_lmt_lft_rep_prc_3m_cash_1m,
  t18.min_rsk_avl_lmt_3m_bt_ch,
  t18.rsk_lmt_rate_ch_1m_grt_0p9_cnt_6m,
  t18.min_rsk_lmt_rate_12m_bt_ch,
  t19.ddf_24m_rep_dte_neg_7_crt_dt_ord_cnt,
  t19.ddf_36m_rep_dte_neg_5_crt_dt_rep_prc_amt_rto,
  t20.m1_rep_apl_suc_amt_avg,
  t21.sum_talk_duration_30d,
  t21.sum_talk_duration_180d,
  t22.rsk_lmt_rate_ch_1m_grt_0p2_rate_36m,
  t23.m6_stg_pln_rep_apl_cnt_equal_1_manual_rep_apl_amt_max,
  t24.lag_his_rep_amt_sum_per_mth_btch_rat_max,
  t25.credit_fund_level2_reject_cnt_36m,
  t25.credit_min_limit_cnt_all,
  t26.stg_pln_pay_off_sum_prc_amt_1m_3m_rto,
  t27.`3stg_pln_repay_amt_first_der_stddev`,
  t28.d90_repaid_exclude_principal_fee_stddev,
  t28.d1080_sum_repaid_interest_fee_sum_divide_d1080_principal_sum,
  t29.max_rsk_avl_lmt_bjq_12m_all,
  t30.sum_avb_lmt_2m_v2,
  t31.`18m_repay_ftr_amt_second_der_mean_diff`,
  t32.stg_pln_pay_off_sum_prc_amt_14d,
  t33.min_ddf_mdl_rep_dte_his_bjq
from (
  select
  sample_row_num,
  uid,
  mdl_dte,
  blue_customer_flag,
  ftr_30d_ord_flag,
  ftr_30d_ord_amt,
  prc_amt_xz_30d_3m,
  ovd_amt_xz_30d_3m,
  liushi_days,
  due_date_flag,
  final_flag,
  fq_diff_grp,
  mob_group,
  zc_level,
  gd_lmt_grp,
  gcard_v2,
  gcard_v4,
  gcard_v5,
  gcard_v6,
  rand_flag0,
  rand_flag1,
  rand_flag2,
  rand_flag3,
  rand_flag4,
  rand_flag5,
  ds
  from pdm_risk.pdm_risk_gcard_base_sample_uid_ds_eva_ben_v6_1
  where ds is not null
) t1
left join (
  select
  uid,
  mdl_dte,
  ord_apl_sum_prc_amt_90_day,
  ord_apl_max_prc_amt_180_day,
  ord_apl_sum_prc_amt_360_day,
  his_180_day_csh_apl_ord_cnt_his_rto,
  his_360_day_csh_apl_ord_cnt,
  his_360_day_csh_apl_ord_cnt_his_rto,
  ord_apl_min_prc_amt_his,
  ord_apl_fal_cnt_his,
  ord_apl_cnt_90_day_07_12,
  ord_apl_fal_cnt_360_day,
  his_90_day_csh_apl_ord_cnt_his_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_7fst_9all_10cur_11lst_orders_info_df_feature
  where ds is not null
) t2
  on t1.uid = t2.uid and t1.mdl_dte = t2.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  d360_apl_ord_ddf_mdl_ord_crt_dte_min,
  d180_apl_ord_days_cnt_all,
  d360_apl_ord_cnt_all,
  d360_apl_ord_prc_amt_min,
  d360_apl_ord_ddf_mdl_ord_crt_dte_max,
  d60_d90_apl_ord_cnt_rat_all,
  d15_d360_apl_ord_prc_amt_avg_rat,
  d30_d360_suc_ord_prc_amt_avg_rat_all,
  d30_d90_suc_ord_prc_amt_avg_rat_all
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dz_model_final_order_info_df_feature
  where ds is not null
) t3
  on t1.uid = t3.uid and t1.mdl_dte = t3.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  unpaid_principal_future_light_add_heavy
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_30light_cross_heavy_inner_behaviour_df_feature
  where ds is not null
) t4
  on t1.uid = t4.uid and t1.mdl_dte = t4.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  dau_90d,
  ddf_mdl_max_con_dau_dt_90d,
  max_con_dau_7d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_dau_feature
  where ds is not null
) t5
  on t1.uid = t5.uid and t1.mdl_dte = t5.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  cnt_event_result_1_uid_recent_days_120,
  cnt_other_info_cash_uid_recent_days_30,
  first_day_diff_event_result_0_event_type_loan_all,
  max_amt_other_info_manual_repay,
  div_amt_event_type_repay_loan
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_22pip_heavy_cross_info_df_feature
  where ds is not null
) t6
  on t1.uid = t6.uid and t1.mdl_dte = t6.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  ddf_lst_app_str_tim_to_mdl_tim_sec
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_device_extra_1_df_feature
  where ds is not null
) t7
  on t1.uid = t7.uid and t1.mdl_dte = t7.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  cnt_avg_ord_span_30d,
  cnt_avg_ord_span_30d_90d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_22order_calculate_stage_order_info_df_feature
  where ds is not null
) t8
  on t1.uid = t8.uid and t1.mdl_dte = t8.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  d90_aplord_suc_month_cnt
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_off_dp_dz_inner_behavior_order_enhanced_aggregation_feature
  where ds is not null
) t9
  on t1.uid = t9.uid and t1.mdl_dte = t9.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  clk_cnt_14d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_8active_page_view_n_click_cnt_feature
  where ds is not null
) t10
  on t1.uid = t10.uid and t1.mdl_dte = t10.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  rsk_avl_lmt_ch_les_500_cnt_12m,
  rsk_avl_lmt_ch_les_10000_cnt_3m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dz_model_account_lmt_feature_sample_final_df_feature
  where ds is not null
) t11
  on t1.uid = t11.uid and t1.mdl_dte = t11.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  stg_pln_max_rep_prc_1m_his
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_ability_df_feature
  where ds is not null
) t12
  on t1.uid = t12.uid and t1.mdl_dte = t12.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  m1_stg_pln_d0_rep_apl_cnt,
  m6_stg_pln_d0_normal_batch_rep_apl_suc_cnt_rat
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_3_feature
  where ds is not null
) t13
  on t1.uid = t13.uid and t1.mdl_dte = t13.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  his_720_day_csh_apl_ord_cnt_his_rto,
  ord_apl_cnt_07_12
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_7fst_9all_10cur_11lst_orders_info_new_df_feature
  where ds is not null
) t14
  on t1.uid = t14.uid and t1.mdl_dte = t14.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  stg_pln_sum_prc_amt_12m_ftr_his_rep_rto_cash,
  stg_pln_sum_prc_amt_6m_12m_ftr_rto_cash,
  stg_pln_cnt_3m_ftr_adv_rto_all
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_14ftr_rep_pressure_trend_df_feature
  where ds is not null
) t15
  on t1.uid = t15.uid and t1.mdl_dte = t15.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  d360_due_repay_amt_avg_divide_d360_faqi_trade_amt_avg,
  his_due_repay_amt_sum_divide_his_faqi_trade_amt_sum,
  d720_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  d1080_due_repay_amt_sum_divide_d1080_faqi_trade_amt_sum,
  his_trade_fail_amt_sum_mon_divide_his_trade_success_amt_sum_mon,
  d90_due_repay_amt_avg_divide_d90_faqi_trade_amt_avg,
  d360_max_faqi_prc_amt_divide_rsk_avl_lmt_cash,
  his_due_repay_amt_avg_divide_his_faqi_trade_amt_avg,
  d1080_max_faqi_prc_amt_divide_rsk_adt_lmt_cash,
  d180_due_repay_amt_avg_divide_d180_faqi_trade_amt_avg,
  d180_unpaid_principal_tot_amt_t_day_divide_rsk_avl_lmt_cash_his_t_day_max,
  his_max_due_prc_amt_divide_his_max_faqi_prc_amt,
  d1080_due_repay_amt_avg_divide_d1080_faqi_trade_amt_avg,
  his_max_faqi_prc_amt_divide_max_ontim_amt_sum_mon,
  d180_ontimrepay_thismon_sum_larger_than_rsk_avl_lmt_cash_count_sum,
  d720_faqi_trade_amt_larger_than_unpaid_principal_tot_amt_t_day_count_sum,
  his_max_faqi_prc_amt_divide_unpaid_principal_tot,
  d720_due_repay_amt_sum_divide_d720_faqi_trade_amt_sum,
  his_trade_fail_count_mon_divide_his_trade_success_count_mon
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_25_cross_inner_behaviour_df_feature
  where ds is not null
) t16
  on t1.uid = t16.uid and t1.mdl_dte = t16.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  `18m_used_lmt_second_der_min`,
  `6m_used_lmt_first_der_min`,
  `6m_used_lmt_second_der_min`,
  `12m_used_lmt_second_der_sum`,
  `6m_used_lmt_first_der_sum`,
  `12m_used_lmt_second_der_mean_diff`,
  `6m_used_lmt_second_der_sum`,
  `18m_used_lmt_first_der_sum`,
  `6m_used_lmt_first_der_max`,
  `3m_used_lmt_second_der_sum`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_used_lmt_trend_time_series_df_feature
  where ds is not null
) t17
  on t1.uid = t17.uid and t1.mdl_dte = t17.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  avg_avl_lmt_lft_rep_prc_3m_cash_1m,
  min_rsk_avl_lmt_3m_bt_ch,
  rsk_lmt_rate_ch_1m_grt_0p9_cnt_6m,
  min_rsk_lmt_rate_12m_bt_ch
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_df_feature
  where ds is not null
) t18
  on t1.uid = t18.uid and t1.mdl_dte = t18.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  ddf_24m_rep_dte_neg_7_crt_dt_ord_cnt,
  ddf_36m_rep_dte_neg_5_crt_dt_rep_prc_amt_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_16draw_repay_crossed_new_df_feature
  where ds is not null
) t19
  on t1.uid = t19.uid and t1.mdl_dte = t19.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  m1_rep_apl_suc_amt_avg
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_1_feature
  where ds is not null
) t20
  on t1.uid = t20.uid and t1.mdl_dte = t20.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  sum_talk_duration_30d,
  sum_talk_duration_180d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_pdm_risk_dh_model_final_13collection_call_info_trend_features_di_feature
  where ds is not null
) t21
  on t1.uid = t21.uid and t1.mdl_dte = t21.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  rsk_lmt_rate_ch_1m_grt_0p2_rate_36m
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_new_df_feature
  where ds is not null
) t22
  on t1.uid = t22.uid and t1.mdl_dte = t22.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  m6_stg_pln_rep_apl_cnt_equal_1_manual_rep_apl_amt_max
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_rep_apply_summary_4_feature
  where ds is not null
) t23
  on t1.uid = t23.uid and t1.mdl_dte = t23.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  lag_his_rep_amt_sum_per_mth_btch_rat_max
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_12his_rep_pressure_trend_df_feature
  where ds is not null
) t24
  on t1.uid = t24.uid and t1.mdl_dte = t24.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  credit_fund_level2_reject_cnt_36m,
  credit_min_limit_cnt_all
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_31light_credit_trade_cross_df_feature
  where ds is not null
) t25
  on t1.uid = t25.uid and t1.mdl_dte = t25.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  stg_pln_pay_off_sum_prc_amt_1m_3m_rto
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_derived_df_feature
  where ds is not null
) t26
  on t1.uid = t26.uid and t1.mdl_dte = t26.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  `3stg_pln_repay_amt_first_der_stddev`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_his_rep_trend_time_series_df_feature
  where ds is not null
) t27
  on t1.uid = t27.uid and t1.mdl_dte = t27.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  d90_repaid_exclude_principal_fee_stddev,
  d1080_sum_repaid_interest_fee_sum_divide_d1080_principal_sum
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_26_lending_costs_detail_df_feature
  where ds is not null
) t28
  on t1.uid = t28.uid and t1.mdl_dte = t28.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  max_rsk_avl_lmt_bjq_12m_all
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_account_lmt_feature_sample_all_final_jqh_df_feature
  where ds is not null
) t29
  on t1.uid = t29.uid and t1.mdl_dte = t29.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  sum_avb_lmt_2m_v2
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_5account_extra_df_feature
  where ds is not null
) t30
  on t1.uid = t30.uid and t1.mdl_dte = t30.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  `18m_repay_ftr_amt_second_der_mean_diff`
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_ftr_rep_trend_time_series_df_feature
  where ds is not null
) t31
  on t1.uid = t31.uid and t1.mdl_dte = t31.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  stg_pln_pay_off_sum_prc_amt_14d
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_df_feature
  where ds is not null
) t32
  on t1.uid = t32.uid and t1.mdl_dte = t32.mdl_dte
left join (
  select
  uid,
  mdl_dte,
  min_ddf_mdl_rep_dte_his_bjq
  from ads_app_off_feature.ds29531_backtrack_fj_gcard_model_v6_1_dwa_risk_dz_model_final_12his_rep_will_pressure_jqh_df_feature
  where ds is not null
) t33
  on t1.uid = t33.uid and t1.mdl_dte = t33.mdl_dte
;
